### ISSUE TITLE
IsPrimaryKey  property

### ISSUE THREAD

**Issue by amalsharief** [pdevito3/craftsman#37]
Hi,
Are you changing how to deal with primary keys?

No problems with running  craftsman version 0.11.1 
but, will produce the following error when run on a clone of dev branch, Am I missing something?

YamlException: (Line: 39, Col: 7, Idx: 1089) - (Line: 39, Col: 7, Idx: 1089): Exception during deserialization
     SerializationException: Property 'IsPrimaryKey' not found on type 'Craftsman.Models.EntityProperty'.
       at GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
       at GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
       at Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
       at DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   ....
   .....

**Comment by pdevito3** [comment]
Assuming this master/develop for the upcoming v0.12? 

If so yes, I have items for it briefly in the changelog but essentially you just don't add a PK property in your yaml anymore since all entities will now inherit from a new BaseEntity class that has the PK on it.

I went back and forth in this for a while as it's pretty opinionated, but it makes maintenance and features a lot easier and I do want to have some conventions for the project as well so while it definitely tows the line, it seemed like a good long term move. 

Regardless, just drop the the PK property from your yaml and it should run fine.

**Comment by amalsharief** [comment]
Thank you,

I was about to ask you about adding a base class, I think it will make life
easy.

Abdoessalam
