### ISSUE TITLE
Migrate from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by sshquack** [pdevito3/craftsman#52]
# Problem I am trying to solve
- Improve default performance, security and standards compliance of Json ser/deser
- Currently the default scaffold builders use Newtonsoft.Json [here](https://github.com/pdevito3/craftsman/search?q=%22using+newtonsoft.json%3B%22+path%3A%2FCraftsman%2FBuilders&type=)
- The .NET team has written a detailed article on System.Text.Json [here](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/)
- The migration guide lists the problems it solves and the gaps in comparison to Newtonsoft.Json [here](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-6-0)
- The MassTransit project is migrating to System.Text.Json and saw a 2x increase in performance while using less memory [here](https://twitter.com/PhatBoyG/status/1480291539213553665) and [here](https://github.com/MassTransit/MassTransit/discussions/2727#discussioncomment-1901390).

# Solution I'd like
- Make System.Text.Json the default. Since a lot of web APIs rely on JSON ser/de-ser, this allows newcomers to realize the performance benefits while eliminating security risk and improving JSON standards compliance.

I'd love to contribute this change, if this is something that sounds interesting to you!

**Comment by pdevito3** [comment]
Hey! Yeah, this definitely sounds reasonable for `HttpClientExtensionsBuilder`. 

I want to say that I remember there being a weird gap on the json attributes being used in entity builder that required both options when working with relationships and the `Startup` config also plays into that to a degree. Of course I didn't document the issue though so I might not be able to repo it though...

With that said, I'm open to giving it a try and if it does break I can document it and move it back until there is a fix since we're still pre-v1. 

I'd love it if you were able to contribute! I haven't had enough interest yet to put together a `Contributing.md` and the project is definitely still messy in some areas, but hopefully it's straight forward enough. Essentially, you'd go into the builder files that you linked and update the scaffolding for each to whatever is appropriate. When you're ready to try the scaffolding, you can run it locally, most easily with a `dotnet run new:example` command. It will prompt you for a directory to toss the example in when running it locally like this and then it operates as normal. You don't need to worry about tests yet as I don't want to dump time into them yet until the project is more stable.

**Comment by Jogai** [comment]
Maybe use something like this: https://github.com/Open-NET-Libraries/Open.Serialization so projects still can make the choice.

**Comment by sshquack** [comment]
@pdevito3 Great -- I'll take a crack at it and get a PR for this too shortly. No worries on the contributing doc. Thanks for the pointers on where to look. I'll mention you when it's ready.

**Comment by pdevito3** [comment]
Awesome, appreciate ya! I've got a really packed week with work, but I want to sink some time into craftsman this weekend! Feel free to ping me here or in discord if you have any questions
