### ISSUE TITLE
UserPolicyHandler doesn't generate the defined DbContext name

### ISSUE THREAD

**Issue by ogkushmin** [pdevito3/craftsman#70]
When the UserPolicyHandler generates it uses RecipesDbContext instead of the defined context name from the definition file.

**Comment by pdevito3** [comment]
Whoops, nice find! I'll definitely get this fixed in the upcoming release.

Also, thanks so much for the sponsorship! Not seeing a way to shoot you a message privately, but I would be more than happy to add your name to a new sponsors section on the Wrapt website with a link to anywhere of your choosing as well as a twitter shout out! If you're interested shoot me your details at pdevito3@gmail.com and I'll get you sorted. Thanks again!
