### ISSUE TITLE
ForeignEntity property name is being generated with the entity name vs the name

### ISSUE THREAD

**Issue by ogkushmin** [pdevito3/craftsman#90]
I have an entity defined with foreign entities, when the code is generated it is ignoring the property name and using the foreignentityname. 

### Steps to reproduce
-yaml
- Name: Advertiser
        TableName: Advertiser
        Features:
        - Type: GetRecord
        - Type: GetList
        - Type: DeleteRecord
          IsProtected: true
          PermissionName: candelete
        - Type: UpdateRecord
          IsProtected: true
          PermissionName: canupdate
        - Type: PatchRecord
          IsProtected: true
          PermissionName: canupdate
        - Type: AddRecord
          IsProtected: true
          PermissionName: canadd
        Properties:
          - Name: Name
            Type: string
            CanFilter: true
            CanSort: true
          - Name: CreatedBy
            Type: User
            ForeignEntityName: User
            CanFilter: true
            CanSort: true
          - Name: ModifiedBy
            Type: User
            ForeignEntityName: User
            CanFilter: true
            CanSort: true

##Output
using Ordering.Domain.Users;
using Ordering.Domain.Users;

[Table("Advertiser")]
public class Advertiser : BaseEntity
{
    [Sieve(CanFilter = true, CanSort = true)]
    public virtual string Name { get; private set; }

    [JsonIgnore]
    [IgnoreDataMember]
    [Sieve(CanFilter = true, CanSort = true)]
    public virtual User User { get; private set; }

    [JsonIgnore]
    [IgnoreDataMember]
    [Sieve(CanFilter = true, CanSort = true)]
    public virtual User User { get; private set; }

**Comment by pdevito3** [comment]
hmm, interesting. Will try and take a look at this later tonight!

**Comment by pdevito3** [comment]
About to head out to an event, so can't dig in deep at the moment, but at first glance you might want to try something like this:

```yaml
      - Name: CreatedById
        Type: Guid
        ForeignEntityName: User
        ForeignEntityPlural: Users
      - Name: ModifiedById
        Type: Guid
        ForeignEntityName: User
        ForeignEntityPlural: Users
```

If I'm remembering that part of the codebase correctly, it needs the Id property and will make the entity based on off of the given info automatically something like this with just the entity might not work at the moment. Can think though options to make things more flexible if that is the case though.

Even if the above does work you might need to make minor mods as it will probably add the `User` prop twice similar to what is already happening because there's no check to see if it's already there

**Comment by pdevito3** [comment]
able to repro and yeah it shouldn't be happening that way. digging now!

**Comment by pdevito3** [comment]
found it. thanks for the callout!
